apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databox-cms-data
  labels:
    app.kubernetes.io/name: databox-cms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
