export const PLATFORM_ONTOLOGIES = [
  // Enterprise
  { id: "ent-salesforce", name: "Salesforce", category: "Enterprise" },
  { id: "ent-oracle", name: "Oracle Cloud", category: "Enterprise" },
  { id: "ent-sap", name: "SAP", category: "Enterprise" },
  { id: "ent-workday", name: "Workday", category: "Enterprise" },
  { id: "ent-hubspot", name: "HubSpot", category: "Enterprise" },
  { id: "ent-zendesk", name: "Zendesk", category: "Enterprise" },
  { id: "ent-atlassian", name: "Atlassian", category: "Enterprise" },
  { id: "ent-microsoft365", name: "Microsoft 365", category: "Enterprise" },
  { id: "ent-slack", name: "Slack", category: "Enterprise" },
  { id: "ent-servicenow", name: "ServiceNow", category: "Enterprise" },
  { id: "ent-splunk", name: "Splunk", category: "Enterprise" },
  { id: "ent-datadog", name: "Datadog", category: "Enterprise" },
  { id: "ent-snowflake", name: "Snowflake", category: "Enterprise" },
  { id: "ent-box", name: "Box", category: "Enterprise" },
  { id: "ent-dropbox", name: "Dropbox", category: "Enterprise" },
  { id: "ent-okta", name: "Okta", category: "Enterprise" },
  { id: "ent-zoom", name: "Zoom", category: "Enterprise" },
  { id: "ent-webex", name: "Cisco Webex", category: "Enterprise" },
  { id: "ent-adobe", name: "Adobe", category: "Enterprise" },
  { id: "ent-adp", name: "ADP", category: "Enterprise" },
  { id: "ent-bamboohr", name: "BambooHR", category: "Enterprise" },
  { id: "ent-gusto", name: "Gusto", category: "Enterprise" },
  { id: "ent-deel", name: "Deel", category: "Enterprise" },
  { id: "ent-rippling", name: "Rippling", category: "Enterprise" },
  { id: "ent-paycom", name: "Paycom", category: "Enterprise" },
  { id: "ent-paylocity", name: "Paylocity", category: "Enterprise" },
  { id: "ent-sapsuccessfactors", name: "SuccessFactors", category: "Enterprise" },
  { id: "ent-ukg", name: "UKG", category: "Enterprise" },
  { id: "ent-workato", name: "Workato", category: "Enterprise" },
  { id: "ent-zapier", name: "Zapier", category: "Enterprise" },
  { id: "ent-mulesoft", name: "MuleSoft", category: "Enterprise" },
  { id: "ent-boomi", name: "Boomi", category: "Enterprise" },
  { id: "ent-asana", name: "Asana", category: "Enterprise" },
  { id: "ent-monday", name: "Monday.com", category: "Enterprise" },
  { id: "ent-smartsheet", name: "Smartsheet", category: "Enterprise" },
  { id: "ent-airtable", name: "Airtable", category: "Enterprise" },
  { id: "ent-notion", name: "Notion", category: "Enterprise" },
  { id: "ent-trello", name: "Trello", category: "Enterprise" },
  { id: "ent-github", name: "GitHub", category: "Enterprise" },
  { id: "ent-gitlab", name: "GitLab", category: "Enterprise" },
  { id: "ent-bitbucket", name: "Bitbucket", category: "Enterprise" },
  { id: "ent-pagerduty", name: "PagerDuty", category: "Enterprise" },
  { id: "ent-newrelic", name: "New Relic", category: "Enterprise" },
  { id: "ent-appdynamics", name: "AppDynamics", category: "Enterprise" },
  { id: "ent-dynatrace", name: "Dynatrace", category: "Enterprise" },
  { id: "ent-crowdstrike", name: "CrowdStrike", category: "Enterprise" },
  { id: "ent-paloalto", name: "Palo Alto", category: "Enterprise" },
  { id: "ent-fortinet", name: "Fortinet", category: "Enterprise" },
  { id: "ent-xero", name: "Xero", category: "Enterprise" },
  { id: "ent-quickbooks", name: "QuickBooks", category: "Enterprise" },

  // Consumer
  { id: "con-google", name: "Google", category: "Consumer" },
  { id: "con-meta", name: "Meta", category: "Consumer" },
  { id: "con-apple", name: "Apple", category: "Consumer" },
  { id: "con-microsoft", name: "Microsoft", category: "Consumer" },
  { id: "con-amazon", name: "Amazon", category: "Consumer" },
  { id: "con-tiktok", name: "TikTok", category: "Consumer" },
  { id: "con-x", name: "X (Twitter)", category: "Consumer" },
  { id: "con-snapchat", name: "Snapchat", category: "Consumer" },
  { id: "con-pinterest", name: "Pinterest", category: "Consumer" },
  { id: "con-reddit", name: "Reddit", category: "Consumer" },
  { id: "con-linkedin", name: "LinkedIn", category: "Consumer" },
  { id: "con-discord", name: "Discord", category: "Consumer" },
  { id: "con-twitch", name: "Twitch", category: "Consumer" },
  { id: "con-whatsapp", name: "WhatsApp", category: "Consumer" },
  { id: "con-telegram", name: "Telegram", category: "Consumer" },
  { id: "con-signal", name: "Signal", category: "Consumer" },
  { id: "con-wechat", name: "WeChat", category: "Consumer" },
  { id: "con-line", name: "Line", category: "Consumer" },
  { id: "con-kakaotalk", name: "KakaoTalk", category: "Consumer" },
  { id: "con-viber", name: "Viber", category: "Consumer" },
  { id: "con-spotify", name: "Spotify", category: "Consumer" },
  { id: "con-netflix", name: "Netflix", category: "Consumer" },
  { id: "con-disneyplus", name: "Disney+", category: "Consumer" },
  { id: "con-hulu", name: "Hulu", category: "Consumer" },
  { id: "con-hbomax", name: "Max (HBO)", category: "Consumer" },
  { id: "con-primevideo", name: "Prime Video", category: "Consumer" },
  { id: "con-appletv", name: "Apple TV+", category: "Consumer" },
  { id: "con-youtube", name: "YouTube", category: "Consumer" },
  { id: "con-soundcloud", name: "SoundCloud", category: "Consumer" },
  { id: "con-pandora", name: "Pandora", category: "Consumer" },
  { id: "con-applemusic", name: "Apple Music", category: "Consumer" },
  { id: "con-tidal", name: "Tidal", category: "Consumer" },
  { id: "con-siriusxm", name: "SiriusXM", category: "Consumer" },
  { id: "con-playstation", name: "PlayStation", category: "Consumer" },
  { id: "con-xbox", name: "Xbox", category: "Consumer" },
  { id: "con-nintendo", name: "Nintendo", category: "Consumer" },
  { id: "con-steam", name: "Steam", category: "Consumer" },
  { id: "con-epicgames", name: "Epic Games", category: "Consumer" },
  { id: "con-roblox", name: "Roblox", category: "Consumer" },
  { id: "con-minecraft", name: "Minecraft", category: "Consumer" },
  { id: "con-fitbit", name: "Fitbit", category: "Consumer" },
  { id: "con-garmin", name: "Garmin", category: "Consumer" },
  { id: "con-strava", name: "Strava", category: "Consumer" },
  { id: "con-myfitnesspal", name: "MyFitnessPal", category: "Consumer" },
  { id: "con-peloton", name: "Peloton", category: "Consumer" },
  { id: "con-oura", name: "Oura", category: "Consumer" },
  { id: "con-whoop", name: "Whoop", category: "Consumer" },
  { id: "con-healthkit", name: "HealthKit", category: "Consumer" },
  { id: "con-googlefit", name: "Google Fit", category: "Consumer" },
  { id: "con-samsunghealth", name: "Samsung Health", category: "Consumer" },

  // Retail
  { id: "ret-amazon", name: "Amazon Retail", category: "Retail" },
  { id: "ret-shopify", name: "Shopify", category: "Retail" },
  { id: "ret-walmart", name: "Walmart", category: "Retail" },
  { id: "ret-target", name: "Target", category: "Retail" },
  { id: "ret-ebay", name: "eBay", category: "Retail" },
  { id: "ret-etsy", name: "Etsy", category: "Retail" },
  { id: "ret-wayfair", name: "Wayfair", category: "Retail" },
  { id: "ret-homedepot", name: "Home Depot", category: "Retail" },
  { id: "ret-lowes", name: "Lowe's", category: "Retail" },
  { id: "ret-bestbuy", name: "Best Buy", category: "Retail" },
  { id: "ret-costco", name: "Costco", category: "Retail" },
  { id: "ret-samsclub", name: "Sam's Club", category: "Retail" },
  { id: "ret-ikea", name: "IKEA", category: "Retail" },
  { id: "ret-macys", name: "Macy's", category: "Retail" },
  { id: "ret-nordstrom", name: "Nordstrom", category: "Retail" },
  { id: "ret-sephora", name: "Sephora", category: "Retail" },
  { id: "ret-ulta", name: "Ulta Beauty", category: "Retail" },
  { id: "ret-chewy", name: "Chewy", category: "Retail" },
  { id: "ret-zappos", name: "Zappos", category: "Retail" },
  { id: "ret-asos", name: "ASOS", category: "Retail" },
  { id: "ret-zara", name: "Zara", category: "Retail" },
  { id: "ret-hm", name: "H&M", category: "Retail" },
  { id: "ret-uniqlo", name: "Uniqlo", category: "Retail" },
  { id: "ret-shein", name: "SHEIN", category: "Retail" },
  { id: "ret-temu", name: "Temu", category: "Retail" },
  { id: "ret-wish", name: "Wish", category: "Retail" },
  { id: "ret-alibaba", name: "Alibaba", category: "Retail" },
  { id: "ret-taobao", name: "Taobao", category: "Retail" },
  { id: "ret-jd", name: "JD.com", category: "Retail" },
  { id: "ret-rakuten", name: "Rakuten", category: "Retail" },
  { id: "ret-mercadolibre", name: "Mercado Libre", category: "Retail" },
  { id: "ret-flipkart", name: "Flipkart", category: "Retail" },
  { id: "ret-myntra", name: "Myntra", category: "Retail" },
  { id: "ret-nykaa", name: "Nykaa", category: "Retail" },
  { id: "ret-bigbasket", name: "BigBasket", category: "Retail" },
  { id: "ret-instacart", name: "Instacart", category: "Retail" },
  { id: "ret-shipt", name: "Shipt", category: "Retail" },
  { id: "ret-gopuff", name: "GoPuff", category: "Retail" },
  { id: "ret-drizly", name: "Drizly", category: "Retail" },
  { id: "ret-totalwine", name: "Total Wine", category: "Retail" },
  { id: "ret-walgreens", name: "Walgreens", category: "Retail" },
  { id: "ret-cvs", name: "CVS", category: "Retail" },
  { id: "ret-riteaid", name: "Rite Aid", category: "Retail" },
  { id: "ret-boots", name: "Boots", category: "Retail" },
  { id: "ret-nike", name: "Nike", category: "Retail" },
  { id: "ret-adidas", name: "Adidas", category: "Retail" },
  { id: "ret-lululemon", name: "Lululemon", category: "Retail" },
  { id: "ret-underarmour", name: "Under Armour", category: "Retail" },

  // Gig Economy
  { id: "gig-uber", name: "Uber", category: "Gig Economy" },
  { id: "gig-lyft", name: "Lyft", category: "Gig Economy" },
  { id: "gig-didi", name: "DiDi", category: "Gig Economy" },
  { id: "gig-grab", name: "Grab", category: "Gig Economy" },
  { id: "gig-gojek", name: "Gojek", category: "Gig Economy" },
  { id: "gig-ola", name: "Ola", category: "Gig Economy" },
  { id: "gig-bolt", name: "Bolt", category: "Gig Economy" },
  { id: "gig-cabify", name: "Cabify", category: "Gig Economy" },
  { id: "gig-careem", name: "Careem", category: "Gig Economy" },
  { id: "gig-freenow", name: "FreeNow", category: "Gig Economy" },
  { id: "gig-ubereats", name: "Uber Eats", category: "Gig Economy" },
  { id: "gig-doordash", name: "DoorDash", category: "Gig Economy" },
  { id: "gig-deliveroo", name: "Deliveroo", category: "Gig Economy" },
  { id: "gig-grubhub", name: "Grubhub", category: "Gig Economy" },
  { id: "gig-postmates", name: "Postmates", category: "Gig Economy" },
  { id: "gig-skipthedishes", name: "SkipTheDishes", category: "Gig Economy" },
  { id: "gig-justeat", name: "Just Eat", category: "Gig Economy" },
  { id: "gig-deliveryhero", name: "Delivery Hero", category: "Gig Economy" },
  { id: "gig-foodpanda", name: "Foodpanda", category: "Gig Economy" },
  { id: "gig-zomato", name: "Zomato", category: "Gig Economy" },
  { id: "gig-swiggy", name: "Swiggy", category: "Gig Economy" },
  { id: "gig-taskrabbit", name: "TaskRabbit", category: "Gig Economy" },
  { id: "gig-upwork", name: "Upwork", category: "Gig Economy" },
  { id: "gig-fiverr", name: "Fiverr", category: "Gig Economy" },
  { id: "gig-toptal", name: "Toptal", category: "Gig Economy" },
  { id: "gig-freelancer", name: "Freelancer", category: "Gig Economy" },
  { id: "gig-thumbtack", name: "Thumbtack", category: "Gig Economy" },
  { id: "gig-handy", name: "Handy", category: "Gig Economy" },
  { id: "gig-rover", name: "Rover", category: "Gig Economy" },
  { id: "gig-wag", name: "Wag", category: "Gig Economy" },
  { id: "gig-carecom", name: "Care.com", category: "Gig Economy" },
  { id: "gig-sittercity", name: "Sittercity", category: "Gig Economy" },
  { id: "gig-airtasker", name: "AirTasker", category: "Gig Economy" },
  { id: "gig-airbnb", name: "Airbnb", category: "Gig Economy" },
  { id: "gig-vrbo", name: "Vrbo", category: "Gig Economy" },
  { id: "gig-booking", name: "Booking.com", category: "Gig Economy" },
  { id: "gig-expedia", name: "Expedia", category: "Gig Economy" },
  { id: "gig-agoda", name: "Agoda", category: "Gig Economy" },
  { id: "gig-tripcom", name: "Trip.com", category: "Gig Economy" },
  { id: "gig-skyscanner", name: "Skyscanner", category: "Gig Economy" },
  { id: "gig-kayak", name: "Kayak", category: "Gig Economy" },
  { id: "gig-hopper", name: "Hopper", category: "Gig Economy" },
  { id: "gig-getaround", name: "Getaround", category: "Gig Economy" },
  { id: "gig-turo", name: "Turo", category: "Gig Economy" },
  { id: "gig-zipcar", name: "Zipcar", category: "Gig Economy" },
  { id: "gig-lime", name: "Lime", category: "Gig Economy" },
  { id: "gig-bird", name: "Bird", category: "Gig Economy" },
  { id: "gig-spin", name: "Spin", category: "Gig Economy" },

  // Fintech
  { id: "fin-stripe", name: "Stripe", category: "Fintech" },
  { id: "fin-paypal", name: "PayPal", category: "Fintech" },
  { id: "fin-square", name: "Square", category: "Fintech" },
  { id: "fin-adyen", name: "Adyen", category: "Fintech" },
  { id: "fin-braintree", name: "Braintree", category: "Fintech" },
  { id: "fin-checkout", name: "Checkout.com", category: "Fintech" },
  { id: "fin-klarna", name: "Klarna", category: "Fintech" },
  { id: "fin-afterpay", name: "Afterpay", category: "Fintech" },
  { id: "fin-affirm", name: "Affirm", category: "Fintech" },
  { id: "fin-sezzle", name: "Sezzle", category: "Fintech" },
  { id: "fin-zip", name: "Zip", category: "Fintech" },
  { id: "fin-revolut", name: "Revolut", category: "Fintech" },
  { id: "fin-monzo", name: "Monzo", category: "Fintech" },
  { id: "fin-n26", name: "N26", category: "Fintech" },
  { id: "fin-starling", name: "Starling", category: "Fintech" },
  { id: "fin-chime", name: "Chime", category: "Fintech" },
  { id: "fin-varo", name: "Varo", category: "Fintech" },
  { id: "fin-nubank", name: "Nubank", category: "Fintech" },
  { id: "fin-wise", name: "Wise", category: "Fintech" },
  { id: "fin-remitly", name: "Remitly", category: "Fintech" },
  { id: "fin-worldremit", name: "WorldRemit", category: "Fintech" },
  { id: "fin-westernunion", name: "Western Union", category: "Fintech" },
  { id: "fin-moneygram", name: "MoneyGram", category: "Fintech" },
  { id: "fin-plaid", name: "Plaid", category: "Fintech" },
  { id: "fin-tink", name: "Tink", category: "Fintech" },
  { id: "fin-truelayer", name: "Truelayer", category: "Fintech" },
  { id: "fin-yodlee", name: "Yodlee", category: "Fintech" },
  { id: "fin-envestnet", name: "Envestnet", category: "Fintech" },
  { id: "fin-coinbase", name: "Coinbase", category: "Fintech" },
  { id: "fin-binance", name: "Binance", category: "Fintech" },
  { id: "fin-kraken", name: "Kraken", category: "Fintech" },
  { id: "fin-gemini", name: "Gemini", category: "Fintech" },
  { id: "fin-cryptocom", name: "Crypto.com", category: "Fintech" },
  { id: "fin-robinhood", name: "Robinhood", category: "Fintech" },
  { id: "fin-etoro", name: "eToro", category: "Fintech" },
  { id: "fin-webull", name: "Webull", category: "Fintech" },
  { id: "fin-sofi", name: "SoFi", category: "Fintech" },
  { id: "fin-betterment", name: "Betterment", category: "Fintech" },
  { id: "fin-wealthfront", name: "Wealthfront", category: "Fintech" },
  { id: "fin-acorns", name: "Acorns", category: "Fintech" },
  { id: "fin-stash", name: "Stash", category: "Fintech" },
  { id: "fin-mint", name: "Mint", category: "Fintech" },
  { id: "fin-ynab", name: "YNAB", category: "Fintech" },
  { id: "fin-personalcapital", name: "Personal Capital", category: "Fintech" },
  { id: "fin-rocketmortgage", name: "Rocket Mortgage", category: "Fintech" },
  { id: "fin-bettercom", name: "Better.com", category: "Fintech" },
  { id: "fin-lendingclub", name: "LendingClub", category: "Fintech" },
  { id: "fin-prosper", name: "Prosper", category: "Fintech" },
  { id: "fin-upstart", name: "Upstart", category: "Fintech" },

  // Healthcare
  { id: "hea-epic", name: "Epic", category: "Healthcare" },
  { id: "hea-cerner", name: "Cerner", category: "Healthcare" },
  { id: "hea-meditech", name: "MEDITECH", category: "Healthcare" },
  { id: "hea-allscripts", name: "Allscripts", category: "Healthcare" },
  { id: "hea-athenahealth", name: "Athenahealth", category: "Healthcare" },
  { id: "hea-eclinicalworks", name: "eClinicalWorks", category: "Healthcare" },
  { id: "hea-nextgen", name: "NextGen", category: "Healthcare" },
  { id: "hea-greenway", name: "Greenway", category: "Healthcare" },
  { id: "hea-practicefusion", name: "Practice Fusion", category: "Healthcare" },
  { id: "hea-kareo", name: "Kareo", category: "Healthcare" },
  { id: "hea-curemd", name: "CureMD", category: "Healthcare" },
  { id: "hea-modernizing", name: "Modernizing Medicine", category: "Healthcare" },
  { id: "hea-drchrono", name: "DrChrono", category: "Healthcare" },
  { id: "hea-advancedmd", name: "AdvancedMD", category: "Healthcare" },
  { id: "hea-webpt", name: "WebPT", category: "Healthcare" },
  { id: "hea-therabill", name: "Therabill", category: "Healthcare" },
  { id: "hea-simplepractice", name: "SimplePractice", category: "Healthcare" },
  { id: "hea-teladoc", name: "Teladoc", category: "Healthcare" },
  { id: "hea-amwell", name: "Amwell", category: "Healthcare" },
  { id: "hea-mdlive", name: "MDLive", category: "Healthcare" },
  { id: "hea-doctorondemand", name: "Doctor on Demand", category: "Healthcare" },
  { id: "hea-babylonhealth", name: "Babylon Health", category: "Healthcare" },
  { id: "hea-khealth", name: "K Health", category: "Healthcare" },
  { id: "hea-ro", name: "Ro", category: "Healthcare" },
  { id: "hea-himsandhers", name: "Hims & Hers", category: "Healthcare" },
  { id: "hea-goodrx", name: "GoodRx", category: "Healthcare" },
  { id: "hea-singlecare", name: "SingleCare", category: "Healthcare" },
  { id: "hea-pillpack", name: "PillPack", category: "Healthcare" },
  { id: "hea-altopharmacy", name: "Alto Pharmacy", category: "Healthcare" },
  { id: "hea-capsule", name: "Capsule", category: "Healthcare" },
  { id: "hea-zocdoc", name: "Zocdoc", category: "Healthcare" },
  { id: "hea-healthgrades", name: "Healthgrades", category: "Healthcare" },
  { id: "hea-vitals", name: "Vitals", category: "Healthcare" },
  { id: "hea-mychart", name: "MyChart", category: "Healthcare" },
  { id: "hea-followmyhealth", name: "FollowMyHealth", category: "Healthcare" },
  { id: "hea-healow", name: "Healow", category: "Healthcare" },
  { id: "hea-caresync", name: "CareSync", category: "Healthcare" },
  { id: "hea-sharecare", name: "Sharecare", category: "Healthcare" },
  { id: "hea-virginpulse", name: "Virgin Pulse", category: "Healthcare" },
  { id: "hea-castlight", name: "Castlight", category: "Healthcare" },
  { id: "hea-grandrounds", name: "Grand Rounds", category: "Healthcare" },
  { id: "hea-accolade", name: "Accolade", category: "Healthcare" },
  { id: "hea-quantumhealth", name: "Quantum Health", category: "Healthcare" },
  { id: "hea-evidation", name: "Evidation", category: "Healthcare" },
  { id: "hea-23andme", name: "23andMe", category: "Healthcare" },
  { id: "hea-ancestrydna", name: "AncestryDNA", category: "Healthcare" },
  { id: "hea-myheritage", name: "MyHeritage", category: "Healthcare" },
  { id: "hea-color", name: "Color", category: "Healthcare" },
  { id: "hea-invitae", name: "Invitae", category: "Healthcare" },
  { id: "hea-natera", name: "Natera", category: "Healthcare" },

  // Utilities
  { id: "uti-telstra", name: "Telstra", category: "Utilities" },
  { id: "uti-optus", name: "Optus", category: "Utilities" },
  { id: "uti-tpg", name: "TPG", category: "Utilities" },
  { id: "uti-vodafone", name: "Vodafone", category: "Utilities" },
  { id: "uti-att", name: "AT&T", category: "Utilities" },
  { id: "uti-verizon", name: "Verizon", category: "Utilities" },
  { id: "uti-tmobile", name: "T-Mobile", category: "Utilities" },
  { id: "uti-sprint", name: "Sprint", category: "Utilities" },
  { id: "uti-bt", name: "BT", category: "Utilities" },
  { id: "uti-sky", name: "Sky", category: "Utilities" },
  { id: "uti-virginmedia", name: "Virgin Media", category: "Utilities" },
  { id: "uti-o2", name: "O2", category: "Utilities" },
  { id: "uti-ee", name: "EE", category: "Utilities" },
  { id: "uti-three", name: "Three", category: "Utilities" },
  { id: "uti-orange", name: "Orange", category: "Utilities" },
  { id: "uti-telefonica", name: "Telefonica", category: "Utilities" },
  { id: "uti-telecomitalia", name: "Telecom Italia", category: "Utilities" },
  { id: "uti-deutschetelekom", name: "Deutsche Telekom", category: "Utilities" },
  { id: "uti-swisscom", name: "Swisscom", category: "Utilities" },
  { id: "uti-kpn", name: "KPN", category: "Utilities" },
  { id: "uti-proximus", name: "Proximus", category: "Utilities" },
  { id: "uti-telenor", name: "Telenor", category: "Utilities" },
  { id: "uti-telia", name: "Telia", category: "Utilities" },
  { id: "uti-singtel", name: "Singtel", category: "Utilities" },
  { id: "uti-starhub", name: "StarHub", category: "Utilities" },
  { id: "uti-m1", name: "M1", category: "Utilities" },
  { id: "uti-nttdocomo", name: "NTT Docomo", category: "Utilities" },
  { id: "uti-kddi", name: "KDDI", category: "Utilities" },
  { id: "uti-softbank", name: "SoftBank", category: "Utilities" },
  { id: "uti-chinamobile", name: "China Mobile", category: "Utilities" },
  { id: "uti-chinatelecom", name: "China Telecom", category: "Utilities" },
  { id: "uti-chinaunicom", name: "China Unicom", category: "Utilities" },
  { id: "uti-originenergy", name: "Origin Energy", category: "Utilities" },
  { id: "uti-agl", name: "AGL", category: "Utilities" },
  { id: "uti-energyaustralia", name: "EnergyAustralia", category: "Utilities" },
  { id: "uti-pge", name: "PG&E", category: "Utilities" },
  { id: "uti-sce", name: "Southern California Edison", category: "Utilities" },
  { id: "uti-conedison", name: "Con Edison", category: "Utilities" },
  { id: "uti-dukeenergy", name: "Duke Energy", category: "Utilities" },
  { id: "uti-nextera", name: "NextEra", category: "Utilities" },
  { id: "uti-exelon", name: "Exelon", category: "Utilities" },
  { id: "uti-dominion", name: "Dominion", category: "Utilities" },
  { id: "uti-nationalgrid", name: "National Grid", category: "Utilities" },
  { id: "uti-edf", name: "EDF", category: "Utilities" },
  { id: "uti-engie", name: "Engie", category: "Utilities" },
  { id: "uti-eon", name: "E.ON", category: "Utilities" },
  { id: "uti-enel", name: "Enel", category: "Utilities" },
  { id: "uti-iberdrola", name: "Iberdrola", category: "Utilities" },
  { id: "uti-rwe", name: "RWE", category: "Utilities" },
  { id: "uti-vattenfall", name: "Vattenfall", category: "Utilities" }
];
