use std::{fs, process::Command};
use serde_json::json;

use crate::shape::{display_path, InstallProfile};

pub fn run(profile: &InstallProfile) -> Result<(), String> {
    fs::create_dir_all(profile.data_dir()).map_err(|error| format!("Could not create the data folder: {error}"))?;
    fs::create_dir_all(profile.logs_dir()).map_err(|error| format!("Could not create the log folder: {error}"))?;
    let keys_dir = profile.data_dir().join("keys");
    fs::create_dir_all(&keys_dir).map_err(|error| format!("Could not create the keys folder: {error}"))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&keys_dir, fs::Permissions::from_mode(0o700)).map_err(|error| error.to_string())?;
    }

    let token = random_token();
    let native_edge = profile.native_edge_binary.as_ref().map(|name| profile.binary_path(name));
    let env_file = format!("# Generated by Databox setup. Keep this file private.\nBASE_URL=http://localhost:{}/\nCMS_CONFIG={}\nCMS_CONTROL_TOKEN={}\nCSS_STORAGE_PATH={}\nPOS_EDGE_BINARY={}\nPOS_HTTP_PORT=9100\n",
        profile.required_port, profile.config_preset, token, display_path(&profile.data_dir().join("storage")), native_edge.as_ref().map(|path| display_path(path)).unwrap_or_default());
    fs::create_dir_all(profile.data_dir().join("storage")).map_err(|error| error.to_string())?;
    fs::write(profile.app_dir().join(".env"), env_file).map_err(|error| format!("Could not save configuration: {error}"))?;

    let desktop = json!({
        "appDir": profile.app_dir(),
        "nodePath": profile.node_binary_path(),
        "configPreset": profile.config_preset,
        "adminUrl": format!("http://localhost:{}/.databox/cms/admin", profile.required_port),
        "logsDir": profile.logs_dir(),
        "posEdgePath": native_edge,
        "startOnLaunch": true,
    });
    fs::write(profile.desktop_config_path(), serde_json::to_vec_pretty(&desktop).map_err(|error| error.to_string())?)
        .map_err(|error| format!("Could not save desktop configuration: {error}"))?;
    println!("  Created private configuration and local storage");

    let node = if profile.node_binary_path().is_file() { profile.node_binary_path() } else { "node".into() };
    let script = "const {generateKeyPairSync}=require('crypto'); const fs=require('fs'); const p=process.argv[1]; const k=generateKeyPairSync('rsa',{modulusLength:2048,publicKeyEncoding:{type:'spki',format:'pem'},privateKeyEncoding:{type:'pkcs8',format:'pem'}}); fs.writeFileSync(p+'/oidc-private.pem',k.privateKey,{mode:0o600}); fs.writeFileSync(p+'/oidc-public.pem',k.publicKey);";
    let result = Command::new(node).args(["-e", script, &display_path(&keys_dir)]).output();
    if !matches!(result, Ok(output) if output.status.success()) { return Err("Could not generate local signing keys.".to_owned()); }
    Ok(())
}

fn random_token() -> String {
    use rand::RngCore;
    let mut bytes = [0_u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}
