use crate::shape::InstallProfile;

/// Step 5: Configuration & cryptography bootstrap.
/// Generates .env, signing keys, and initializes storage paths.
pub fn run(profile: &InstallProfile) -> Result<(), String> {
    let data_dir = profile.data_dir();
    let app_dir = profile.app_dir();

    std::fs::create_dir_all(&data_dir)
        .map_err(|e| format!("Failed to create data dir: {}", e))?;

    // Generate .env file
    let env_path = format!("{}/.env", app_dir);
    let control_token = generate_random_token();
    let base_url = "http://localhost:3000/";

    let env_content = format!(
        r#"# Databox CMS environment — generated by installer
BASE_URL={}
CMS_CONFIG={}
CMS_CONTROL_TOKEN={}
# Storage
CSS_STORAGE_PATH={}
# Native edge (POS)
POS_EDGE_BINARY={}
POS_HTTP_PORT={}
POS_PRINTER_DEVICE={}
POS_DISPLAY_DEVICE={}
POS_CASH_DRAWER_VIA={}
"#,
        base_url,
        profile.config_preset,
        control_token,
        data_dir,
        profile.native_edge_binary.as_deref().unwrap_or(""),
        profile.native_edge_http_port,
        profile.printer_device.as_deref().unwrap_or(""),
        profile.display_device.as_deref().unwrap_or(""),
        profile.cash_drawer_via,
    );

    std::fs::write(&env_path, &env_content)
        .map_err(|e| format!("Failed to write .env: {}", e))?;

    println!("  Generated .env at {}", env_path);
    println!("  Control token: {}...{} (full token in .env)", &control_token[..8], &control_token[control_token.len()-4..]);
    println!("  Data directory: {}", data_dir);

    // Create initial storage structure
    let storage_path = format!("{}/storage", data_dir);
    std::fs::create_dir_all(&storage_path)
        .map_err(|e| format!("Failed to create storage dir: {}", e))?;

    let config_path = format!("{}/config", data_dir);
    std::fs::create_dir_all(&config_path)
        .map_err(|e| format!("Failed to create config dir: {}", e))?;

    let keys_path = format!("{}/keys", data_dir);
    std::fs::create_dir_all(&keys_path)
        .map_err(|e| format!("Failed to create keys dir: {}", e))?;

    // Set restrictive permissions on the keys directory
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&keys_path, std::fs::Permissions::from_mode(0o700))
            .map_err(|e| format!("Failed to set keys dir permissions: {}", e))?;
    }

    println!("  Created storage structure: storage/, config/, keys/");

    // Generate Solid-OIDC signing keys via the Node binary if available
    let node_binary = profile.node_binary_path();
    let node_available = std::path::Path::new(&node_binary).exists()
        || std::process::Command::new("node").arg("-v").output().is_ok();

    if node_available {
        let keygen_script = r#"
const { generateKeyPairSync } = require('crypto');
const { writeFileSync } = require('fs');
const { join } = require('path');

const { privateKey, publicKey } = generateKeyPairSync('rsa', {
  modulusLength: 2048,
  publicKeyEncoding: { type: 'spki', format: 'pem' },
  privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
});

const keysDir = process.argv[2];
writeFileSync(join(keysDir, 'oidc-private.pem'), privateKey, { mode: 0o600 });
writeFileSync(join(keysDir, 'oidc-public.pem'), publicKey);
console.log('Generated Solid-OIDC RSA key pair');
"#;
        let script_path = format!("{}/keygen.cjs", keys_path);
        std::fs::write(&script_path, keygen_script)
            .map_err(|e| format!("Failed to write keygen script: {}", e))?;

        let node_cmd = if std::path::Path::new(&node_binary).exists() {
            &node_binary
        } else {
            "node"
        };

        let output = std::process::Command::new(node_cmd)
            .arg(&script_path)
            .arg(&keys_path)
            .output();

        match output {
            Ok(result) if result.status.success() => {
                println!("  Generated Solid-OIDC signing keys in keys/");
                // Clean up the script
                let _ = std::fs::remove_file(&script_path);
            }
            Ok(result) => {
                let stderr = String::from_utf8_lossy(&result.stderr);
                println!("  Warning: key generation failed: {}", stderr.trim());
                println!("  You will need to generate OIDC keys manually.");
                let _ = std::fs::remove_file(&script_path);
            }
            Err(e) => {
                println!("  Warning: could not execute Node for key generation: {}", e);
                println!("  You will need to generate OIDC keys manually.");
                let _ = std::fs::remove_file(&script_path);
            }
        }
    } else {
        println!("  Warning: Node.js not available for key generation.");
        println!("  You will need to generate OIDC keys manually after Node is installed.");
    }

    Ok(())
}

fn generate_random_token() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 32];
    rand::rng().fill_bytes(&mut bytes);
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}
