apiVersion: v1
kind: ConfigMap
metadata:
  name: databox-ipms-config
  labels:
    app.kubernetes.io/name: databox-ipms
data:
  CSS_BASE_URL: 'https://databox.example.org/'
  CSS_CONFIG: config/ipms/ipms-file.json
  CSS_PORT: '3000'
  CSS_ROOT_FILE_PATH: /data
  CSS_LOGGING_LEVEL: info
