apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databox-ipms-data
  labels:
    app.kubernetes.io/name: databox-ipms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
