name: Continuous Integration

on:
  push:
    branches:
      - main
      - 'versions/**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  package:
    name: Package
    needs: verify
    uses: ./.github/workflows/package.yml
