name: CI
on:
  push:
    branches:
      - main
      - 'versions/*'
    tags:
      - 'v*'
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  npm-test:
    # Run the test suite
    uses: ./.github/workflows/npm-test.yml

  build:
    # Build Server, Admin Demo, and cross-platform native binaries
    uses: ./.github/workflows/build.yml

  cth-test:
    # Run the Conformance Test Harness
    uses: ./.github/workflows/cth-test.yml
    with:
      ignore_failures: true
      version: 1.1.14 # The latest version that CSS is confirmed to pass

  mkdocs-release:
    # Build and deploy documentation
    if: startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main'
    uses: ./.github/workflows/mkdocs.yml
    permissions:
      contents: write

  cross-release:
    # Publish release artifacts to GitHub Releases on version tags
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
